spring.application.name=coworking

spring.datasource.url=jdbc:postgresql://localhost:5432/cowork_db
spring.datasource.name=postgres
spring.datasource.password=postgres

jwt_secret=0dbf8cf40c4f40cbef18acb11e1d5833b7c2ed7b837a556c22ca132f125ca285